application: healthio-dev
version: bb-authorization-form
api_version: 1
runtime: python27
threadsafe: false

libraries:
- name: jinja2
  version: "2.6"

handlers:

- url: /static
  static_dir: frontend/static

- url: /.*
  script: main.application
  secure: always

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?.*\.so$
- ^(.*/)?.*\_test.(html|js|py)$
